Repository WildCodeSchool-2024-02/JS-RMT-julien-FilmParadise-Project2, pull requests merged in 2024-05, with the labels that each got.

#1 Route@config
  client/index.html
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/assets/favicon.ico
  client/src/assets/fonts/Philosopher-Regular.ttf
  client/src/assets/fonts/Righteous-Regular.ttf
  client/src/components/header/Header.jsx
  client/src/components/header/header.css
  client/src/main.jsx
  client/src/pages/AllMovies.jsx
  client/src/pages/MovieDetail.jsx
  server/app/router.js
  server/database/data.js
Labels: CORRECTIONS DONE, REVIEWED

#2 Movie cards@feat
  client/.eslintrc.json
  client/src/App.css
  client/src/components/MovieCard/MovieCard.jsx
  client/src/components/MovieCard/movie-card.css
  client/src/main.jsx
  client/src/pages/AllMovies.jsx
  server/app/router.js
Labels: CORRECTIONS DONE, REVIEWED

#5 mise en pklace du context
  client/.eslintrc.json
  client/src/context/MovieContext.jsx
  client/src/main.jsx
Labels: REVIEWED

#4 Navigation@feat
  client/index.html
  client/src/App.jsx
  client/src/assets/images/Logo.png
  client/src/assets/images/background.webp
  client/src/components/header/Header.jsx
  client/src/components/header/header.css
  client/src/main.jsx
  client/src/pages/Cart.jsx
Labels: CORRECTIONS DONE, REVIEWED

#3 Movie details@feat
  client/src/components/MovieDetailCard/Details.jsx
  client/src/components/MovieDetailCard/MovieDetail.css
  client/src/components/MovieDetailCard/MovieDetailCard.jsx
  client/src/main.jsx
  client/src/pages/MovieDetail.jsx
  server/app/router.js
Labels: REVIEWED

#6 Database@feat
  server/database/schema.sql
Labels: REVIEW REQUESTED, REVIEWED

#7 Config@style
  client/index.html
  client/src/App.css
  client/src/assets/images/Logo.ico
  client/src/components/MovieCard/movie-card.css
  client/src/components/MovieDetailCard/MovieDetail.css
  client/src/components/header/Header.jsx
  client/src/components/header/header.css
  client/src/pages/AllMovies.jsx
  client/src/pages/MovieDetail.jsx
Labels: CHANGES REQUESTED

#8 récupération du background en local
  client/index.html
  client/src/App.css
  client/src/App.jsx
  client/src/assets/images/background.avif
  client/src/components/header/Header.jsx
  client/src/components/header/header.css
Labels: CORRECTIONS DONE, REVIEWED

#9 configuration de la route api pour tous les films avec database
  server/app/router.js
Labels: REVIEWED

#10 configuration de la route details des films
  server/app/router.js
Labels: CORRECTIONS DONE, REVIEWED

#11 Add to cart@feat
  client/src/App.jsx
  client/src/components/AddToCart/ButtonCart.jsx
  client/src/components/AddToCart/addToCart.css
  client/src/components/MovieDetailCard/MovieDetailCard.jsx
  client/src/context/MovieContext.jsx
  client/src/main.jsx
Labels: CORRECTIONS DONE, REVIEWED
