Repository WildCodeSchool-2024-02/JS-RMT-julien-FilmParadise-Project2, pull requests merged in 2024-06, with the labels that each got.

#12 Cart page@feat
  client/src/App.css
  client/src/components/CartDetails/CartDetails.css
  client/src/components/CartDetails/CartDetails.jsx
  client/src/components/MovieCard/MovieCard.jsx
  client/src/components/MovieCard/movie-card.css
  client/src/components/header/Header.jsx
  client/src/main.jsx
  client/src/pages/AllMovies.jsx
  client/src/pages/Cart.jsx
Labels: REVIEWED

#13 Add favory@feat
  client/src/assets/images/heart-empty.png
  client/src/assets/images/heart-red.png
  client/src/components/AddFavory/AddFavory.jsx
  client/src/components/AddFavory/addFavory.css
  client/src/components/AddToCart/addToCart.css
  client/src/components/CartDetails/CartDetails.jsx
  client/src/components/MovieCard/MovieCard.jsx
  client/src/components/MovieCard/movie-card.css
  client/src/components/MovieDetailCard/MovieDetail.css
  client/src/components/MovieDetailCard/MovieDetailCard.jsx
  client/src/context/MovieContext.jsx
  client/src/pages/AllMovies.jsx
Labels: CONFLICTS RESOLVED, REVIEWED

#14 Delete basket@feat
  client/src/assets/images/trash.png
  client/src/components/CartDetails/CartDetails.css
  client/src/components/CartDetails/CartDetails.jsx
  client/src/context/MovieContext.jsx
Labels: REVIEWED

#16 ajustement de la logique pour enlever et ajouter des films au panier…
  client/src/components/AddToCart/ButtonCart.jsx
  client/src/components/AddToCart/addToCart.css
  client/src/components/CartDetails/CartDetails.jsx
  client/src/context/MovieContext.jsx
Labels: REVIEWED

#17 Searchbar@feat
  client/src/App.jsx
  client/src/assets/images/loupe.png
  client/src/components/SearchBar/SearchBar.css
  client/src/components/SearchBar/SearchBar.jsx
  client/src/components/header/Header.jsx
  client/src/components/header/header.css
  client/src/main.jsx
  client/src/pages/AllMovies.jsx
  server/app/router.js
Labels: REVIEWED

#21 ajout des placeholders dans les inputs, modifications du CSS du formulaire.
  client/src/components/Footer/Formulaire.jsx
  client/src/components/Footer/footer.css
Labels: REVIEWED

#20 ajout du footer sur toutes les pages et placement de ce dernier en ba…
  client/src/App.css
  client/src/components/Footer/footer.css
  client/src/pages/AllMovies.jsx
  client/src/pages/Cart.jsx
  client/src/pages/MovieDetail.jsx
Labels: CONFLICTS RESOLVED, REVIEWED

#22 Order form@feat
  client/src/components/CartDetails/CartDetails.css
  client/src/components/OrderForm/OrderForm.css
  client/src/components/OrderForm/OrderForm.jsx
  client/src/context/MovieContext.jsx
  client/src/pages/Cart.jsx
Labels: CORRECTIONS DONE, REVIEWED

#23 debug barre de recherche
  client/src/components/SearchBar/SearchBar.jsx
  client/src/pages/AllMovies.jsx
Labels: CONFLICTS RESOLVED, REVIEWED

#24 Home page@feat
  client/src/App.css
  client/src/App.jsx
  client/src/assets/images/home.png
  client/src/components/header/Header.jsx
  client/src/components/header/header.css
Labels: REVIEWED
